Repository fogbow/resource-allocation-service, pull requests merged in 2020-06, with the labels that each got.

#545 Make Azure Attachment Plugin compatible with Fogbow deletion logic
  src/main/java/cloud/fogbow/ras/core/plugins/interoperability/azure/attachment/AzureAttachmentPlugin.java
  src/test/java/cloud/fogbow/ras/core/plugins/interoperability/azure/attachment/AzureAttachmentPluginTest.java
Labels: bug

#546 Azure fault message feature
  src/main/java/cloud/fogbow/ras/core/plugins/interoperability/azure/AzureAsync.java
  src/main/java/cloud/fogbow/ras/core/plugins/interoperability/azure/attachment/sdk/AzureAttachmentOperationSDK.java
  src/main/java/cloud/fogbow/ras/core/plugins/interoperability/azure/compute/AzureComputePlugin.java
  src/main/java/cloud/fogbow/ras/core/plugins/interoperability/azure/compute/sdk/AzureVirtualMachineOperationSDK.java
  src/main/java/cloud/fogbow/ras/core/plugins/interoperability/azure/network/AzureNetworkPlugin.java
  src/main/java/cloud/fogbow/ras/core/plugins/interoperability/azure/network/sdk/AzureVirtualNetworkOperationSDK.java
  src/main/java/cloud/fogbow/ras/core/plugins/interoperability/azure/publicip/sdk/AzurePublicIPAddressOperationSDK.java
  src/main/java/cloud/fogbow/ras/core/plugins/interoperability/azure/util/AsyncInstanceCreationManager.java
  src/main/java/cloud/fogbow/ras/core/plugins/interoperability/azure/volume/sdk/AzureVolumeOperationSDK.java
  src/test/java/cloud/fogbow/ras/core/plugins/interoperability/azure/AzureAsyncTest.java
  src/test/java/cloud/fogbow/ras/core/plugins/interoperability/azure/attachment/sdk/AzureAttachmentOperationSDKTest.java
  src/test/java/cloud/fogbow/ras/core/plugins/interoperability/azure/compute/AzureComputePluginTest.java
  src/test/java/cloud/fogbow/ras/core/plugins/interoperability/azure/compute/sdk/AzureVirtualMachineOperationSDKTest.java
  src/test/java/cloud/fogbow/ras/core/plugins/interoperability/azure/network/AzureNetworkPluginTest.java
  src/test/java/cloud/fogbow/ras/core/plugins/interoperability/azure/network/sdk/AzureVirtualNetworkOperationSDKTest.java
  src/test/java/cloud/fogbow/ras/core/plugins/interoperability/azure/publicip/sdk/AzurePublicIPAddressOperationSDKTest.java
  src/test/java/cloud/fogbow/ras/core/plugins/interoperability/azure/util/AsyncInstanceCreationManagerTest.java
  src/test/java/cloud/fogbow/ras/core/plugins/interoperability/azure/volume/AzureVolumePluginTest.java
Labels: feature

#548 Fix aws deletion logic
  src/main/java/cloud/fogbow/ras/core/plugins/interoperability/aws/AwsV2CloudUtil.java
  src/main/java/cloud/fogbow/ras/core/plugins/interoperability/aws/AwsV2StateMapper.java
  src/main/java/cloud/fogbow/ras/core/plugins/interoperability/aws/compute/v2/AwsComputePlugin.java
  src/test/java/cloud/fogbow/ras/core/plugins/interoperability/aws/AwsV2CloudUtilTest.java
  src/test/java/cloud/fogbow/ras/core/plugins/interoperability/aws/compute/v2/AwsComputePluginTest.java
Labels: bug

#553 fixes #547
  src/main/java/cloud/fogbow/ras/core/plugins/interoperability/azure/compute/sdk/AzureVirtualMachineOperationSDK.java
  src/test/java/cloud/fogbow/ras/core/plugins/interoperability/azure/compute/sdk/AzureVirtualMachineOperationSDKTest.java
Labels: bug

#554 fixes #552
  src/main/java/cloud/fogbow/ras/core/plugins/interoperability/azure/publicip/sdk/AzurePublicIPAddressOperationSDK.java
  src/main/java/cloud/fogbow/ras/core/plugins/interoperability/azure/publicip/sdk/AzurePublicIPAddressSDK.java
  src/test/java/cloud/fogbow/ras/core/plugins/interoperability/azure/publicip/sdk/AzurePublicIPAddressOperationSDKTest.java
  src/test/java/cloud/fogbow/ras/core/plugins/interoperability/azure/publicip/sdk/AzurePublicIPAddressSDKTest.java
Labels: enhancement

#558 Fix cloudstack deletion logic
  src/main/java/cloud/fogbow/ras/core/plugins/interoperability/cloudstack/attachment/v4_9/AttachmentJobStatusResponse.java
  src/main/java/cloud/fogbow/ras/core/plugins/interoperability/cloudstack/attachment/v4_9/CloudStackAttachmentPlugin.java
  src/main/java/cloud/fogbow/ras/core/plugins/interoperability/cloudstack/compute/v4_9/CloudStackComputePlugin.java
  src/main/java/cloud/fogbow/ras/core/plugins/interoperability/cloudstack/network/v4_9/CloudStackNetworkPlugin.java
  src/main/java/cloud/fogbow/ras/core/plugins/interoperability/cloudstack/publicip/v4_9/CloudStackPublicIpPlugin.java
  src/main/java/cloud/fogbow/ras/core/plugins/interoperability/cloudstack/volume/v4_9/CloudStackVolumePlugin.java
  src/test/java/cloud/fogbow/ras/core/plugins/interoperability/cloudstack/attachment/v4_9/CloudStackAttachmentPluginTest.java
  src/test/java/cloud/fogbow/ras/core/plugins/interoperability/cloudstack/publicip/v4_9/CloudStackPublicIpPluginTest.java
  src/test/java/cloud/fogbow/ras/core/plugins/interoperability/cloudstack/volume/v4_9/CloudStackVolumePluginTest.java
Labels: bug
